In [93]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [94]:
dataset = pd.read_csv('mobil.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [95]:
print(x)

[['BMW' 2020.0 3500000.0]
 ['BMW' 2010.0 2900000.0]
 ['Audi' 2016.0 nan]
 ['Audi' 2012.0 975000.0]
 ['BMW' 2014.0 2350000.0]
 ['Bentley' nan 7600000.0]
 ['Audi' 2014.0 1470000.0]
 ['Audi' nan 1550000.0]
 ['Mercedes-Benz' 2017.0 2350000.0]
 ['Mercedes-Benz' 2013.0 3850000.0]
 ['Mercedes-Benz' 2016.0 nan]
 ['Audi' 2014.0 2250000.0]
 ['BMW' 2015.0 2125000.0]
 ['Mercedes-Benz' 2015.0 1900000.0]]


In [96]:
print(y)

['Cheap' 'Expensive' 'Cheap' 'Expensive' 'Cheap' 'Expensive' 'Cheap'
 'Expensive' 'Cheap' 'Cheap' 'Cheap' 'Cheap' 'Cheap' 'Cheap']


In [97]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [98]:
print(x)

[['BMW' 2020.0 3500000.0]
 ['BMW' 2010.0 2900000.0]
 ['Audi' 2016.0 2735000.0]
 ['Audi' 2012.0 975000.0]
 ['BMW' 2014.0 2350000.0]
 ['Bentley' 2014.6666666666667 7600000.0]
 ['Audi' 2014.0 1470000.0]
 ['Audi' 2014.6666666666667 1550000.0]
 ['Mercedes-Benz' 2017.0 2350000.0]
 ['Mercedes-Benz' 2013.0 3850000.0]
 ['Mercedes-Benz' 2016.0 2735000.0]
 ['Audi' 2014.0 2250000.0]
 ['BMW' 2015.0 2125000.0]
 ['Mercedes-Benz' 2015.0 1900000.0]]


In [99]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [100]:
print(x)

[[0.0 1.0 0.0 0.0 2020.0 3500000.0]
 [0.0 1.0 0.0 0.0 2010.0 2900000.0]
 [1.0 0.0 0.0 0.0 2016.0 2735000.0]
 [1.0 0.0 0.0 0.0 2012.0 975000.0]
 [0.0 1.0 0.0 0.0 2014.0 2350000.0]
 [0.0 0.0 1.0 0.0 2014.6666666666667 7600000.0]
 [1.0 0.0 0.0 0.0 2014.0 1470000.0]
 [1.0 0.0 0.0 0.0 2014.6666666666667 1550000.0]
 [0.0 0.0 0.0 1.0 2017.0 2350000.0]
 [0.0 0.0 0.0 1.0 2013.0 3850000.0]
 [0.0 0.0 0.0 1.0 2016.0 2735000.0]
 [1.0 0.0 0.0 0.0 2014.0 2250000.0]
 [0.0 1.0 0.0 0.0 2015.0 2125000.0]
 [0.0 0.0 0.0 1.0 2015.0 1900000.0]]


In [101]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [102]:
print(y)

[0 1 0 1 0 1 0 1 0 0 0 0 0 0]


In [105]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [104]:
print(x_train)

[[1.0 0.0 0.0 0.0 2016.0 2735000.0]
 [0.0 0.0 0.0 1.0 2016.0 2735000.0]
 [0.0 1.0 0.0 0.0 2014.0 2350000.0]
 [0.0 1.0 0.0 0.0 2010.0 2900000.0]
 [0.0 1.0 0.0 0.0 2015.0 2125000.0]
 [0.0 1.0 0.0 0.0 2020.0 3500000.0]
 [0.0 0.0 0.0 1.0 2015.0 1900000.0]
 [0.0 0.0 0.0 1.0 2013.0 3850000.0]
 [0.0 0.0 0.0 1.0 2017.0 2350000.0]
 [1.0 0.0 0.0 0.0 2014.0 2250000.0]
 [0.0 0.0 1.0 0.0 2014.6666666666667 7600000.0]]


In [106]:
print(x_test)

[[1.0 0.0 0.0 0.0 2012.0 975000.0]
 [1.0 0.0 0.0 0.0 2014.6666666666667 1550000.0]
 [1.0 0.0 0.0 0.0 2014.0 1470000.0]]


In [107]:
print(y_train)

[0 0 0 1 0 0 0 0 0 0 1]


In [109]:
print(y_test)

[1 1 0]


In [110]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [111]:
print(x_train)

[[1.0 0.0 0.0 -0.7559289460184545 0.4336226783689087 -0.2513041886401306]
 [0.0 0.0 0.0 1.3228756555322954 0.4336226783689087 -0.2513041886401306]
 [0.0 1.0 0.0 -0.7559289460184545 -0.40811546199428955
  -0.5041006824384566]
 [0.0 1.0 0.0 -0.7559289460184545 -2.091591742720686 -0.14296283415513375]
 [0.0 1.0 0.0 -0.7559289460184545 0.012753608187309588 -0.651838893099816]
 [0.0 1.0 0.0 -0.7559289460184545 2.1170989590953053 0.2510057276084912]
 [0.0 0.0 0.0 1.3228756555322954 0.012753608187309588 -0.7995771037611754]
 [0.0 0.0 0.0 1.3228756555322954 -0.8289845321758887 0.4808207219706058]
 [0.0 0.0 0.0 1.3228756555322954 0.8544917485505079 -0.5041006824384566]
 [1.0 0.0 0.0 -0.7559289460184545 -0.40811546199428955
  -0.5697621093990608]
 [0.0 0.0 1.0 -0.7559289460184545 -0.12753608187319157 2.9431242329932616]]


In [112]:
print(x_test)

[[1.0 0.0 0.0 -0.7559289460184545 -1.2498536023574878 -1.406945303146764]
 [1.0 0.0 0.0 -0.7559289460184545 -0.12753608187319157 -1.02939209812329]
 [1.0 0.0 0.0 -0.7559289460184545 -0.40811546199428955
  -1.0819212396917732]]
